### ISSUE TITLE
Investigate sharp discontinuities near edges of reachable area

### ISSUE THREAD

**Issue by dfsnow** [dfsnow/travel-time-matrices#2]
Below is a plot of multi-model travel times in Cook County with the following settings:

```
Starting census tract = 17031031502
Departure time = 2021-04-16 20:21:17 CDT
Maximum walking distance = Infinite
Maximum trip duration = 600 minutes
Maximum number of rides = 5
Transit modes = TRANSIT (any mode) + WALKING
Destinations = All census tracts in Illinois ( + a 100 km buffer) reachable with 600 minutes
Walk speed = 3.6 km/h
```

![cook](https://user-images.githubusercontent.com/31494343/115098428-ba9d9e00-9ef5-11eb-8d15-039e1846aa5f.png)

The times and structure here look pretty reasonable to me. However, the sharp discontinuities (quick changes from purple/blue to yellow) really shouldn't be possible. I suspect they have something to do with the OSM network in the area, or maybe the walk speed is too low.

**Comment by eric-mc2** [comment]
@dfsnow For some perverse reason, the plot look discontinuous or smooth depending on whether I've left or inner-joined the travel times onto the tract geometries, even though the left-over rows from the left-join shouldn't make it into the plot.

But only for IL. Haven't haven't seen discontinuities in DC metro or NY metro areas yet.

A hypothesis from Nico is that these are legit and reflect the edge-of-service at the city border

**Comment by dfsnow** [comment]
Let's test with DC and see if we see the same thing. I'm going to play around with some of the other parameters this weekend as well. I think the 3.6 km/h walk speed is probably too slow.
